FROM openjdk:8
ADD target/EmployerPortalApplication-0.0.1-SNAPSHOT.war EmployerPortalApplication-0.0.1-SNAPSHOT.war
EXPOSE 8086
ENTRYPOINT ["java", "-jar", "EmployerPortalApplication-0.0.1-SNAPSHOT.war"]